require("nvim-treesitter.configs").setup({
  highlight = { enable = true, disable = { "vimdoc" } },
  incremental_selection = { enable = false },
  indent = { enable = false },
  textobjects = { enable = false },
  ensure_installed = {
    "bash",
    "c",
    "cpp",
    "css",
    "go",
    "html",
    "javascript",
    "jsdoc",
    "json",
    "lua",
    "luadoc",
    "luap",
    "markdown",
    "markdown_inline",
    "python",
    "query",
    "regex",
    "rust",
    "toml",
    "typescript",
    "vim",
    "vimdoc",
    "yaml",
  },
})
